### ISSUE TITLE
只是python3 有难度，按照python2.7 xp卡+torch1.1.0+torchvision0.3.0可以运行

### ISSUE THREAD

**Issue by alice-cool** [jokieleung/CL-VQA#1]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512, 2048]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True)

**Comment by alice-cool** [comment]
For using the original feature, because "heng-yu bottom up and down" ,process can't produce bin feature file.
So I use the following in dataset.py，
fe=torch.load('data/rcnn_feature/'+str(img_id)+'.pth'**,encoding='ISO-8859-1'**)['image_feature']

**Comment by alice-cool** [comment]
For running code, I found that because"inplace=True" cause the broke. So I use the inplace=False
![image](https://user-images.githubusercontent.com/16870890/190326764-d93f21d4-cb1a-4c50-b7f0-452191591cb6.png)
![image](https://user-images.githubusercontent.com/16870890/190326824-60b0913d-8ecf-407c-b4a6-6d65b67f37c3.png)

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/190333144-443c4e00-719b-4d4e-90d5-411fe0cd5127.png)

**Comment by jokieleung** [comment]
Your problem should come from the invalid environment, I recommend you use the recommended environment.
